#pragma config(Sensor, in1,    MobilePotL,     sensorPotentiometer)
#pragma config(Sensor, in2,    MobilePotR,     sensorPotentiometer)
#pragma config(Sensor, in3,    ArmPotL,        sensorPotentiometer)
#pragma config(Sensor, in4,    ArmPotR,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ClawArmL,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ClawArmR,       sensorDigitalOut)
#pragma config(Sensor, dgtl9,  EncRight,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, EncLeft,        sensorQuadEncoder)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl11)
#pragma config(Motor,  port3,           MobileGoalL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Left2,         tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl11)
#pragma config(Motor,  port5,           TR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           TL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Right2,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl9)
#pragma config(Motor,  port8,           MobileGoalR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Right1,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl9)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int optimalL;
int optimalR;
int ArmUpdateL;
int ArmUpdateR;
int MoptimalL;
int MoptimalR;

task PID_MG()
{
	float mkp = 0.3; //tune
	float mki = 0.00001; //tune
	float mkd = 0.2; //tune

	float mcurrentL ;
	float merrorTl;
	float mlastErrorL = 0;
	float mproportionL;
	float mintegralL;
	float mderivativeL;
	float mcurrentR ;
	float merrorTr;
	float mlastErrorR = 0;
	float mproportionR;
	float mintegralR;
	float mderivativeR;

	while(true){


		float merrorL = MoptimalL - SensorValue[MobilePotL];
		float merrorR = MoptimalR - SensorValue[MobilePotR];
		//PidAtTargetL = abs(SensorValue[ArmPotL] - optimalL) < 50;
		//PidAtTargetR = abs(SensorValue[ArmPotR] - optimalR) < 50;


		if (abs(merrorL) < 200 && merrorL !=0)
		{
			merrorTl = merrorL;
		}
		else{
			merrorTl = 0;
		}

		if (abs(merrorR) < 200 && merrorR !=0)
		{
			merrorTr = merrorR;
		}
		else{
			merrorTr = 0;
		}

		if (abs(merrorTl)> 50 / mki){
			merrorTl = 50 / mki;
		}

		if (merrorL ==0){
			mderivativeL = 0;
		}

		if (abs(merrorTr)> 50 / mki){
			merrorTr = 50 / mki;
		}

		if (merrorR ==0){
			mderivativeR = 0;
		}




		mproportionL = merrorL * mkp;
		mproportionR = merrorR * mkp;
		mintegralL = merrorTl  * mki;
		mintegralR = merrorTr  * mki;
		mderivativeL = (merrorL - mlastErrorL) * mkd;
		mderivativeR = (merrorR - mlastErrorR) * mkd;

		mlastErrorL = merrorL;
		mlastErrorR = merrorR;

		mcurrentL = mproportionL + mintegralL + mderivativeL;
		mcurrentR = mproportionR + mintegralR + mderivativeR;

		motor[MobileGoalR] = mcurrentR;
		motor[MobileGoalL] = mcurrentL;



		wait1Msec(40);

	}
	return;
}

//int drive_optimalL;
//int drive_optimalR;
/*
void MobileGoal_AutoStraight (int MobileGoal_Power){
	if ((vexRT[Btn8U] ==1) || (vexRT[Btn8D]==1)){
		int MG_Left = SensorValue[MobilePotL];
		int MG_Right=SensorValue[MobilePotR] + 100;
		int MG_error = abs (MG_Left - MG_Right);
		float MobileGoal_Constant = 1.1;
while (true){
if (MG_error <= 10){
	motor [ MobileGoalL] = motor[MobileGoalR] = MobileGoal_Power;
}
else{
		if (MG_Left < MG_Right){
			motor [MobileGoalR] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalL] = MobileGoal_Power / MobileGoal_Constant;
		}
		else if (MG_Left > MG_Right){
			motor [MobileGoalL] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalR] = MobileGoal_Power / MobileGoal_Constant;
		}
		else	{
			motor [ MobileGoalL] = motor[MobileGoalR] = MobileGoal_Power;
		}
}
		wait1Msec(40);
}
		}
else {
	return;
}
}
*/


task PID_RD4B()
{
	float kp = 0.5; //tune
	float ki = 0.0001; //tune
	float kd = 0.4; //tune

	float currentL ;
	float errorTl;
	float lastErrorL = 0;
	float proportionL;
	float integralL;
	float derivativeL;
	float currentR ;
	float errorTr;
	float lastErrorR = 0;
	float proportionR;
	float integralR;
	float derivativeR;

	while(true){


		float errorL = optimalL - SensorValue[ArmPotL];
		float errorR = optimalR - SensorValue[ArmPotR];
		//PidAtTargetL = abs(SensorValue[ArmPotL] - optimalL) < 50;
		//PidAtTargetR = abs(SensorValue[ArmPotR] - optimalR) < 50;


		if (abs(errorL) < 200 && errorL !=0)
		{
			errorTl = errorL;
		}
		else{
			errorTl = 0;
		}

		if (abs(errorR) < 200 && errorR !=0)
		{
			errorTr = errorR;
		}
		else{
			errorTr = 0;
		}

		if (abs(errorTl)> 50 / ki){
			errorTl = 50 / ki;
		}

		if (errorL ==0){
			derivativeL = 0;
		}

		if (abs(errorTr)> 50 / ki){
			errorTr = 50 / ki;
		}

		if (errorR ==0){
			derivativeR = 0;
		}




		proportionL = errorL * kp;
		proportionR = errorR * kp;
		integralL = errorTl  * ki;
		integralR = errorTr  * ki;
		derivativeL = (errorL - lastErrorL) * kd;
		derivativeR = (errorR - lastErrorR) * kd;

		lastErrorL = errorL;
		lastErrorR = errorR;

		currentL = proportionL + integralL + derivativeL;
		currentR = proportionR + integralR + derivativeR;

		motor[TL] = -currentR;
		motor[TR] = -currentL;



		wait1Msec(40);

	}
	return;
}


//--------------------------------------------------------------------------------------------------------------------
task main()
{

optimalL = SensorValue [ArmPotL];
optimalR = SensorValue [ArmPotR];
MoptimalL = SensorValue [MobilePotL];
MoptimalR = SensorValue [MobilePotR];
	startTask (PID_RD4B);
	startTask (PID_MG);
	// Set the optimal value so the task wont be confused, and wont move. Start task


	while (true){
		if(vexRT[Btn5U] == 1)
		{
			while(vexRT[Btn5U] ==1) {
				motor [TL] = motor [TR] = 120;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];
				wait1Msec (40);

			}
		}
		else if(vexRT[Btn5D] == 1)
		{
			while(vexRT[Btn5D] ==1) {
				motor [TL] = motor [TR] = -120;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];
				wait1Msec (40);

			}
		}

		else {
		optimalL = ArmUpdateL;
		optimalR = ArmUpdateR;
		}




		if (vexRT[Ch3Xmtr2] != 0){

		float d = vexRT[Ch3Xmtr2] / 127;
		float Ch3_RD4BL = (0.4* pow(d,3)+ 0.6 * d)*127;
				motor [TR]= motor [TL]= Ch3_RD4BL;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];

		}
		else {
		optimalL = ArmUpdateL;
		optimalR = ArmUpdateR;
		}

		//----------------------------------------------------------------------------------------------


		if(vexRT[Btn6U] == 1)
		{

SensorValue [ClawArmL] = SensorValue [ClawArmR] = 1;

		}
		else if(vexRT[Btn6D] == 1)
		{

SensorValue [ClawArmL] = SensorValue [ClawArmR] = 0;

		}

		else {
		}
//-----------------------------------------------------------------------------------------------
		if(vexRT[Btn5UXmtr2] == 1)
		{
SensorValue [ClawArmL] = SensorValue [ClawArmR] = 1;

		}
		else if(vexRT[Btn5DXmtr2] == 1)
		{

SensorValue [ClawArmL] = SensorValue [ClawArmR] = 0;

		}
		else {
		}


//-------------------------------------------------------------------------------------------------TUNING Mobile Goal limits
if (vexRT [Btn8U] ==1) {
	MoptimalL = 1400;
	MoptimalR = 1463;
}

else if (vexRT [Btn8D] ==1) {
	MoptimalL = 3889;
	MoptimalR = 3972;
}
else {
	MoptimalL = SensorValue[MobilePotL];
	MoptimalR = SensorValue[MobilePotR];
}
		//-------------------------------------------------------------------------------------------------TUNING
/*		if(vexRT[Btn6UXmtr2] == 1)
		{
		startTask(PID_MG);
		MoptimalL = 1400;
		MoptimalR = 1463;
		}
		else if(vexRT[Btn6DXmtr2] == 1)
		{

motor[MobileGoalL] = motor [MobileGoalR] = 120;
		MoptimalL = SensorValue[MobilePotL];
		MoptimalR = SensorValue[MobilePotR];
		}
		else
		{
					stopTask(PID_MG);
		//		MoptimalL = SensorValue[MobilePotL];
		//		MoptimalR = SensorValue[MobilePotL];
		}
*/
//---------------------------------------------------------------------------------------------------------------
			//Joystick control main driver
		float ch3_drive;
		float ch1_drive;
		float a = vexRT[Ch3] / 127.0;
		float b = vexRT[Ch1] / 127.0;
		ch3_drive = vexRT[Ch3];//(0.463 * pow(a,3) - 0.069* pow(a,2) - 0.614 * a) * 127;
		ch1_drive = vexRT[Ch1] *0.8; //(0.463 * pow(b,3) - 0.069* pow(b,2) - 0.614 * b) * 127;


		motor[Left1]  = ((ch3_drive) + (ch1_drive));
		motor[Left2]  = ((ch3_drive) + (ch1_drive));
		motor[Right1] = ((ch3_drive) - (ch1_drive));
		motor[Right2] = ((ch3_drive) - (ch1_drive));

		//Equation: 0.463x^3-0.069x^2+0.614x

wait1Msec(40);
	}
}
