#pragma config(Sensor, in1,    a,              sensorPotentiometer)
#pragma config(Sensor, in2,    b,              sensorPotentiometer)
#pragma config(Sensor, in3,    c,              sensorPotentiometer)
#pragma config(Sensor, in4,    d,              sensorPotentiometer)
#pragma config(Sensor, in5,    e,              sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
