#pragma config(Sensor, in1,    MobilePotL,     sensorPotentiometer)
#pragma config(Sensor, in2,    MobilePotR,     sensorPotentiometer)
#pragma config(Sensor, in3,    ArmPotL,        sensorPotentiometer)
#pragma config(Sensor, in4,    ArmPotR,        sensorPotentiometer)
#pragma config(Sensor, in5,    ClawArmPotL,    sensorPotentiometer)
#pragma config(Sensor, in6,    ClawArmPotR,    sensorPotentiometer)
#pragma config(Sensor, dgtl9,  EncRight,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, EncLeft,        sensorQuadEncoder)
#pragma config(Motor,  port1,           Left2,         tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, dgtl11)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl11)
#pragma config(Motor,  port3,           MobileGoalL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ClawArmL,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           TR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           TL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ClawArmR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           MobileGoalR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Right1,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, dgtl9)
#pragma config(Motor,  port10,          Right2,        tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl9)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int optimalL;
int optimalR;
int ArmUpdateL;
int ArmUpdateR;
int MoptimalL;
int MoptimalR;
int CoptimalL;
int CoptimalR;

//this is our first PID function for the 4 bar located in the front. when it is enabled, it is not very strong.
//Another problem is that sometimes the two motors are not in sync perfectly
//The potentiometer we use measures from 0 to 4096 potentiometer counts which covers a range of 240 degrees

//I want to implement a PID near target for the autonomous, so the next function will run when the PID at target is reached. The current
//autonomous is time based


task PID_ClawLift()
{
	float ckp = 0.27; //tune
	float cki = 0.001; //tune
	float ckd = 0.35; //tune

	float ccurrentL ;
	float cerrorTl;
	float clastErrorL = 0;
	float cproportionL;
	float cintegralL;
	float cderivativeL;
	float ccurrentR ;
	float cerrorTr;
	float clastErrorR = 0;
	float cproportionR;
	float cintegralR;
	float cderivativeR;

	while(true){


		float cerrorL = CoptimalL - SensorValue[ClawArmPotL];
		float cerrorR = CoptimalR - SensorValue[ClawArmPotR];
		//PidAtTargetL = abs(SensorValue[ArmPotL] - optimalL) < 50;
		//PidAtTargetR = abs(SensorValue[ArmPotR] - optimalR) < 50;


		if (abs(cerrorL) < 200 && cerrorL !=0)
		{
			cerrorTl = cerrorL;
		}
		else{
			cerrorTl = 0;
		}

		if (abs(cerrorR) < 200 &&cerrorR !=0)
		{
			cerrorTr = cerrorR;
		}
		else{
			cerrorTr = 0;
		}

		if (abs(cerrorTl)> 50 / cki){
			cerrorTl = 50 / cki;
		}

		if (cerrorL ==0){
			cderivativeL = 0;
		}

		if (abs(cerrorTr)> 50 / cki){
			cerrorTr = 50 / cki;
		}

		if (cerrorR ==0){
			cderivativeR = 0;
		}




		cproportionL = cerrorL * ckp;
		cproportionR = cerrorR * ckp;
		cintegralL = cerrorTl  * cki;
		cintegralR = cerrorTr  * cki;
		cderivativeL = (cerrorL - clastErrorL) * ckd;
		cderivativeR = (cerrorR - clastErrorR) * ckd;

		clastErrorL = cerrorL;
		clastErrorR = cerrorR;

		ccurrentL = cproportionL + cintegralL + cderivativeL;
		ccurrentR = cproportionR + cintegralR + cderivativeR;

		motor[ClawArmR] = -ccurrentR;
		motor[ClawArmL] = -ccurrentL;



		wait1Msec(40);

	}
	return;

}

//The mobile goal PID is aimed to guide the mobile goal intake to the correct angle to line up with the mobile goals. The problem is
//that the system is not precise enough

task PID_MG()
{
	float mkp = 0.3; //tune
	float mki = 0.00001; //tune
	float mkd = 0.2; //tune

	float mcurrentL ;
	float merrorTl;
	float mlastErrorL = 0;
	float mproportionL;
	float mintegralL;
	float mderivativeL;
	float mcurrentR ;
	float merrorTr;
	float mlastErrorR = 0;
	float mproportionR;
	float mintegralR;
	float mderivativeR;

	while(true){


		float merrorL = (MoptimalL - SensorValue[MobilePotL]);
		float merrorR = (MoptimalR - SensorValue[MobilePotR]);
		//PidAtTargetL = abs(SensorValue[ArmPotL] - optimalL) < 50;
		//PidAtTargetR = abs(SensorValue[ArmPotR] - optimalR) < 50;


		if (abs(merrorL) < 200 && merrorL !=0)
		{
			merrorTl = merrorL;
		}
		else{
			merrorTl = 0;
		}

		if (abs(merrorR) < 200 && merrorR !=0)
		{
			merrorTr = merrorR;
		}
		else{
			merrorTr = 0;
		}

		if (abs(merrorTl)> 50 / mki){
			merrorTl = 50 / mki;
		}

		if (merrorL ==0){
			mderivativeL = 0;
		}

		if (abs(merrorTr)> 50 / mki){
			merrorTr = 50 / mki;
		}

		if (merrorR ==0){
			mderivativeR = 0;
		}




		mproportionL = merrorL * mkp;
		mproportionR = merrorR * mkp;
		mintegralL = merrorTl  * mki;
		mintegralR = merrorTr  * mki;
		mderivativeL = (merrorL - mlastErrorL) * mkd;
		mderivativeR = (merrorR - mlastErrorR) * mkd;

		mlastErrorL = merrorL;
		mlastErrorR = merrorR;

		mcurrentL = mproportionL + mintegralL + mderivativeL;
		mcurrentR = mproportionR + mintegralR + mderivativeR;

		motor[MobileGoalR] = -mcurrentR;
		motor[MobileGoalL] = -mcurrentL;



		wait1Msec(40);

	}
	return;
}

//int drive_optimalL;
//int drive_optimalR;
/*
void RD4B_AutoStraight (int RD4B){

int RD4B_error = (SensorValue[ArmPotL]+90)-(SensorValue[ArmPotR]);
if (abs(RD4B_error) <= 30){
	motor [TL] = motor[TR] = RD4B;
}
else{
		if ((SensorValue[ArmPotL]+90) < (SensorValue[ArmPotR])){
			motor [MobileGoalR] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalL] = MobileGoal_Power / MobileGoal_Constant;
		}
		else if (MG_Left > MG_Right){
			motor [MobileGoalL] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalR] = MobileGoal_Power / MobileGoal_Constant;
		}
		else	{
			motor [ MobileGoalL] = motor[MobileGoalR] = MobileGoal_Power;
		}
}
		wait1Msec(40);
}
		}
else {
	return;
}
}

*/

//This is a autostraightening code, but I think I did not do it properly since it does not include
//the motions both picking up the mobile goal and placing it down

/*
void MG_AutoStraight (int MobileGoal_Power){
float MobileGoal_Constant = 1.1;
int MG_error = (SensorValue[MobilePotL]+60)-(SensorValue[MobilePotR]);
if (abs(MG_error) <= 30){
	motor [MobileGoalL] = motor[MobileGoalR] = MobileGoal_Power;
}
else{

		if ((SensorValue[MobilePotL]+60) < (SensorValue[MobilePotR])){
			motor [MobileGoalR] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalL] = MobileGoal_Power / MobileGoal_Constant;
		}
		else if ((SensorValue[MobilePotL]+60) > (SensorValue[MobilePotR])){
			motor [MobileGoalL] = MobileGoal_Power * MobileGoal_Constant;
			motor [MobileGoalR] = MobileGoal_Power / MobileGoal_Constant;
		}
		else	{
			motor [ MobileGoalL] = motor[MobileGoalR] = MobileGoal_Power;
		}
}

}
*/


//This is aimed to keep the reverse double four bar lift at the last registered driver position, which can be controlled by both the primary
//joystick and the secondary joystick
//I am worried that the optimal values set by the primary and secondary joysticks may be in conflict with each other

task PID_RD4B()
{
	float kp = 0.5; //tune
	float ki = 0.0001; //tune
	float kd = 0.4; //tune

	float currentL ;
	float errorTl;
	float lastErrorL = 0;
	float proportionL;
	float integralL;
	float derivativeL;
	float currentR ;
	float errorTr;
	float lastErrorR = 0;
	float proportionR;
	float integralR;
	float derivativeR;

	while(true){


		float errorL = optimalL - SensorValue[ArmPotL];
		float errorR = optimalR - SensorValue[ArmPotR];
		//PidAtTargetL = abs(SensorValue[ArmPotL] - optimalL) < 50;
		//PidAtTargetR = abs(SensorValue[ArmPotR] - optimalR) < 50;


		if (abs(errorL) < 200 && errorL !=0)
		{
			errorTl = errorL;
		}
		else{
			errorTl = 0;
		}

		if (abs(errorR) < 200 && errorR !=0)
		{
			errorTr = errorR;
		}
		else{
			errorTr = 0;
		}

		if (abs(errorTl)> 50 / ki){
			errorTl = 50 / ki;
		}

		if (errorL ==0){
			derivativeL = 0;
		}

		if (abs(errorTr)> 50 / ki){
			errorTr = 50 / ki;
		}

		if (errorR ==0){
			derivativeR = 0;
		}




		proportionL = errorL * kp;
		proportionR = errorR * kp;
		integralL = errorTl  * ki;
		integralR = errorTr  * ki;
		derivativeL = (errorL - lastErrorL) * kd;
		derivativeR = (errorR - lastErrorR) * kd;

		lastErrorL = errorL;
		lastErrorR = errorR;

		currentL = proportionL + integralL + derivativeL;
		currentR = proportionR + integralR + derivativeR;

		motor[TL] = -currentR;
		motor[TR] = -currentL;



		wait1Msec(40);

	}
	return;
}

//--------------------------------------------------------------------------
//-------------------------------------------------------------
//--------------------------------------------------------------------------------------------------------------------
task main()
{

optimalL = SensorValue [ArmPotL];
optimalR = SensorValue [ArmPotR];
MoptimalL = SensorValue [MobilePotL];
MoptimalR = SensorValue [MobilePotR];
CoptimalL = SensorValue [ClawArmPotL];
CoptimalR = SensorValue [ClawArmPotR];
	startTask (PID_RD4B);
	startTask (PID_MG);
	startTask (PID_ClawLift);




	while (true){
//motors power and record value
		if(vexRT[Btn5U] == 1)
		{
			while(vexRT[Btn5U] ==1) {
				motor [TL] = 120;
				motor [TR] = 120;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];
				wait1Msec (40);

			}
		}
		else if(vexRT[Btn5D] == 1)
		{
			while(vexRT[Btn5D] ==1) {
				motor [TL] = -120;
				motor [TR] = -120;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];
				wait1Msec (40);

			}
		}

		// PID optimal set to the recorded values
		else {
		optimalL = ArmUpdateL;
		optimalR = ArmUpdateR;

		}


//secondary joystick for reverse double four bar function
//I am trying to stop the task so the optimal values won't be in conflict


		if (vexRT[Ch3Xmtr2] != 0){ //when the joystick is moved
stopTask(PID_RD4B);

		float d = vexRT[Ch3Xmtr2] / 127;
		float Ch3_RD4BL = ((0.4* pow(d,3))+ (0.6 * d))*127;
				motor [TR]= motor [TL]= Ch3_RD4BL;
			ArmUpdateL = 	SensorValue[ArmPotL];
			ArmUpdateR = SensorValue[ArmPotR];

		}

		else {
	startTask (PID_RD4B);
		optimalL = ArmUpdateL;
		optimalR = ArmUpdateR;
		}

		//----------------------------------------------------------------------------------------------

//This is for the four bar (clawlift pid)
		//When one button is pressed, move to up position  (without holding the button)
		//when the other one is pressed, move to the down position (without holding the button)
		//I am considering to maybe set a default position too, but setting the default position to else may
		//require the driver to hold the button...
		//problem, it does not hold its position very well
		//sometimes it may ocillate once or twice

if (vexRT [Btn6U] ==1) {
CoptimalL = 1809;
CoptimalR = 1862;

}

else if (vexRT [Btn6D] ==1) {

CoptimalL = 3470;
CoptimalR = 3400;

}
else {


}
//-----------------------------------------------------------------------------------------------
//secondary joystick for the previous function

if (vexRT [Btn5UXmtr2] ==1) {
CoptimalL = 1809;
CoptimalR = 1862;

}

else if (vexRT [Btn5DXmtr2] ==1) {

CoptimalL = 3470;
CoptimalR = 3501;

}
else {


}
// MOBILE GOAL in take
//press and hold a button to move towards one position
//press and hold the other button to move towards the other position
//We have troubles to make it stop precisely at the two target positions
//also have problem to make sure the two motors run at the exact same speed
if (vexRT [Btn7U] ==1) {

	MoptimalL = 1413;
	MoptimalR = 1729;
}

else if (vexRT [Btn7D] ==1) {
	MoptimalL = 3889;
	MoptimalR = 3972;
}
else {
	MoptimalL = SensorValue[MobilePotL];
	MoptimalR = SensorValue[MobilePotR];
}
		//-------------------------------------------------------------------------------------------------TUNING
//-------------------------------------------------------------------------------------------------TUNING Mobile Goal limits
if (vexRT [Btn6UXmtr2] ==1) {
	MoptimalL = 1400;
	MoptimalR = 1463;
}

else if (vexRT [Btn6DXmtr2] ==1) {
	MoptimalL = 3889;
	MoptimalR = 3972;
}
else {
	MoptimalL = SensorValue[MobilePotL];
	MoptimalR = SensorValue[MobilePotR];
}

//---------------------------------------------------------------------------------------------------------------
			//Joystick control main driver
//this is the drive function
//I tried to use an equation to customize the joystick abit
//the joystick gives linear outputs from -127 (full power back) to 127 (full power forward), 0 is stop
float ch3_drive;
		float ch1_drive;
		float a = vexRT[Ch3] / 127.0;
		float b = vexRT[Ch1] / 127.0;
		ch3_drive = (0.463* (pow(a,3))- (0.069 * pow(a,2)) + (0.614 * a) ) * 127;
		ch1_drive = (0.463* (pow(b,3))- (0.069 * pow(b,2)) + (0.614 * b) ) * 127;


		motor[Left1]  = ((ch3_drive) + (ch1_drive));
		motor[Left2]  = ((ch3_drive) + (ch1_drive));
		motor[Right1] = ((ch3_drive) - (ch1_drive));
		motor[Right2] = ((ch3_drive) - (ch1_drive));

		//Equation: 0.463x^3-0.069x^2+0.614x
wait1Msec(40);
	}
}
