#pragma config(Sensor, in2,    ClawArmPot,     sensorPotentiometer)
#pragma config(Sensor, in5,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl3,  BumpTouch1,     sensorTouch)
#pragma config(Sensor, dgtl6,  Switch2,        sensorTouch)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ClawArmR,      tmotorVex393_MC29, openLoop, reversed)



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int ClawPotMin = 300;
int ClawPotMax = 700;
int Ayush3;
float KP3 = 0.1;
void PID3 (int optimal3)
{
	int error3 = (optimal3 - SensorValue [ClawPot]);
	int output3 = error3 * KP3;
	motor [Claw] = output3;

}


float KP2 = 0.2;

void PID2 (int optimal2)
{
	int error2 = (optimal2 - SensorValue [ClawArmPot]);
	int output2 = error2 * KP2;
	motor [ClawArmR] = output2;

}
int Ayush2;


task main()
{
while(true){
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			while (( SensorValue [Switch2]==0)&&(vexRT[Btn6U] == 1) ){
			motor[ClawArmR] = 70;  		// open
			Ayush2 = SensorValue[ClawArmPot];
	//	}
}
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			while ((SensorValue [BumpTouch1]==0 )&& (vexRT[Btn6D] == 1)){
			motor[ClawArmR] = -50; 		//...close the gripper.
			Ayush2 = SensorValue[ClawArmPot];
	}
	//}
}
		else                      		//Else (neither button is pressed)...
		{
			PID2(Ayush2);   		//...stop the gripper.
	//	{
	//	motor[ClawArmR] = 0;


		}


if(vexRT[Btn5U] == 1)       	//If Button 6U is pressed...
		{
			while ((SensorValue [ClawPot]> 300)&&(vexRT[Btn5U] == 1)){
			motor[Claw] = 50;  		// open
			Ayush3 = SensorValue[ClawPot];
	//	}
	}
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 6D is pressed...
		{
			while ((SensorValue [ClawPot]< 700)&&(vexRT[Btn5D] == 1)){
			motor[Claw] = -50; 		//...close the gripper.
			Ayush3 = SensorValue[ClawPot];
		//}
	}
}
		else                      		//Else (neither button is pressed)...
		{
			PID3(Ayush3);   		//...stop the gripper.

		}


}



}
