#pragma config(Sensor, in1,    ClawArmPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl3,  BumpTouch1,     sensorTouch)
#pragma config(Sensor, dgtl6,  Switch2,        sensorTouch)
#pragma config(Motor,  port7,           ClawArmR,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//bumptouch 1 is on the claw. Lower limit
//Bumptouch 2 is on the tower, upper limit
float KP2 = 0.2;

void PID2 (int optimal2)
{
	int error2 = (optimal2 - SensorValue [ClawArmPot]);
	int output2 = error2 * KP2;
	motor [ClawArmR] = output2;

}
int Ayush2;
task main()
{
while(true){
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			while (( SensorValue [Switch2]==0)&&(vexRT[Btn6U] == 1) ){
			motor[ClawArmR] = 70;  		// open
			Ayush2 = SensorValue[ClawArmPot];
	//	}
}
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			while ((SensorValue [BumpTouch1]==0 )&& (vexRT[Btn6D] == 1)){
			motor[ClawArmR] = -50; 		//...close the gripper.
			Ayush2 = SensorValue[ClawArmPot];
	}
	//}
}
		else                      		//Else (neither button is pressed)...
		{
			PID2(Ayush2);   		//...stop the gripper.
	//	{
	//	motor[ClawArmR] = 0;


		}

}
}
//}
