#pragma config(Sensor, in5,    ClawPot,        sensorPotentiometer)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int ClawPotMin = 300;
int ClawPotMax = 700;
int Ayush3;
float KP3 = 0.1;
void PID3 (int optimal3)
{
	int error3 = (optimal3 - SensorValue [ClawPot]);
	int output3 = error3 * KP3;
	motor [Claw] = output3;

}


task main()
{
	while(true){
		if(vexRT[Btn5U] == 1)       	//If Button 6U is pressed...
		{
			while ((SensorValue [ClawPot]> 300)&&(vexRT[Btn5U] == 1)){
			motor[Claw] = 50;  		// open
			Ayush3 = SensorValue[ClawPot];
	//	}
	}
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 6D is pressed...
		{
			while ((SensorValue [ClawPot]< 700)&&(vexRT[Btn5D] == 1)){
			motor[Claw] = -50; 		//...close the gripper.
			Ayush3 = SensorValue[ClawPot];
		//}
	}
}
		else                      		//Else (neither button is pressed)...
		{
			PID3(Ayush3);   		//...stop the gripper.

		}

		}
	}
