#pragma config(Sensor, in2,    ArmPot,         sensorPotentiometer)
#pragma config(Motor,  port5,           TR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           TL,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  port9,           BL,            tmotorVex393_MC29, openLoop,reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop)
task main()
{
while(true){


//Button Mode
if(vexRT[Btn8U] == 1)       	//If Button 6U is pressed...
		{
			while ((vexRT[Btn8U] == 1) && (SensorValue[ArmPot]>1700 )){
			motor[TL] = 80;
				motor[TR] = 80;
				//	motor[BL] = 50;
					//	motor[BR] = 50;// open

		}
	}
		//}
		else if(vexRT[Btn8D] == 1)  	//Else, if button 6D is pressed...
		{
			while ((vexRT[Btn8D] == 1)  && (SensorValue[ArmPot]< 3400)){
			motor[TL] = -80;
				motor[TR] = -80;
			//		motor[BL] = -50;
					//	motor[BR] = -50;		//...close the gripper.

		//}
	//}
}
}
		else                      		//Else (neither button is pressed)...
		{
			motor[TL] = 0;
				motor[TR] = 0;
			//		motor[BL] = 0;
				//		motor[BR] = 0;
			//
	//	}



		}

}
}
