#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    armPotL,        sensorPotentiometer)
#pragma config(Sensor, in3,    ClawArmPot,     sensorPotentiometer)
#pragma config(Sensor, in4,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, in5,    MobilePot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LeftMotorENC,   sensorRotation)
#pragma config(Sensor, dgtl2,  RightMotorENC,  sensorRotation)
#pragma config(Sensor, dgtl3,  BumpTouch1,     sensorTouch)
#pragma config(Sensor, dgtl4,  BumpTouch2,     sensorTouch)
#pragma config(Sensor, dgtl5,  Switch1,        sensorTouch)
#pragma config(Sensor, dgtl6,  Switch2,        sensorTouch)
#pragma config(Motor,  port1,           MobileGoalR,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ClawArmR,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RLLeft,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RLRight,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          MobileGoalL,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	while(true)
	{
		motor[Left1]  = (vexRT[Ch3] + vexRT[Ch4])*0.9;
		motor[Left2]  = (vexRT[Ch3] + vexRT[Ch4])*0.9;
		motor[Right1] = (vexRT[Ch3] - vexRT[Ch4])*0.9;
		motor[Right2] = (vexRT[Ch3] - vexRT[Ch4])*0.9;

		//-----------------------------------------------------------------------------------------------------------------------------------------------//
		//RD4B Lift


			motor[RLLeft]  = (vexRT[Ch2])*0.9;
			motor[RLRight] = (vexRT[Ch2])*0.9;



		//------------------------------------------------------------------------------------------------------------------------------------------------//

		//claw arm control
		if (vexRT [Btn5U]== 1)
		{

				motor[ClawArmR]= 120;

			if (vexRT [Btn5U]== 0) {
				motor[ClawArmR]= 0;
			}
		}


		if (vexRT [Btn5D]== 1)
		{

				motor[ClawArmR]= -127;


				if (vexRT [Btn5D]== 0){
				motor[ClawArmR]= 0;
			}
		}

		//----------------------------------------------------------------------------------------------------------------------------------------------------//
		// Claw Control -OPEN
		if (vexRT [Btn6U]== 1)
		{

				motor[Claw]= 120;


			if (vexRT [Btn6U]== 1) {
				motor[Claw]= 0;
			}
		}

		//close
		if (vexRT [Btn6D]== 1)
		{

				motor[Claw]= -120;

				if (vexRT [Btn6D]== 1) {
			motor[Claw]= 0;
			}
		}

		//-------------------------------------------------------------------------------------------------------------------------------------------------//
		//Mobilegoal Intake up

		if (vexRT [Btn8L]== 1)
		{

				motor[MobileGoalL]= 100;
				motor[MobileGoalR]=100;



		if (vexRT [Btn8L]== 1) {
				motor[MobileGoalL]= 0;
				motor[MobileGoalR]=0;
			}
		}


		if (vexRT [Btn8D]== 1)
		{

				motor[MobileGoalL]= -100;
				motor[MobileGoalR]=-100;


			if (vexRT [Btn8D]== 1) {
				motor[MobileGoalL]= 0;
				motor[MobileGoalR]=0;
			}
		}

		//-----------------------------------------------------------------------------------------------------------------------------------------------//
	}
	//Below is the main taskmain
}
