#pragma config(Sensor, dgtl1,  RolEnc,         sensorQuadEncoder)
#pragma config(Motor,  port1,           roller,        tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
if (vexRT[Btn5U]) {
	motor [roller] = 120;
}
else if (vexRT[Btn5D]){
	motor [roller] = -120;
}
else
{
motor [roller] = 5;
}

}
}
